Sco\BehaviorsBundle\Entity\CommentRecord:
    type: entity
    repositoryClass: Sco\BehaviorsBundle\Repository\CommentRecordRepository
    table: sco_comment_record
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        className:
            type: string
            length: 255
        objectId:
            type: integer
        createdAt:
            type: datetime
    oneToOne:
        comment:
            targetEntity: Sco\BehaviorsBundle\Entity\Comment
            mappedBy: commentRecord